---
version: "3.9"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: unless-stopped
    ports:
      - 14250:14250 # collector
      - 16686:16686 # Web UI
      - 16685:16685 # gRPC QueryService
    environment:
      - COLLECTOR_OTLP_ENABLED=true